upstream bancho_backend {
    server 127.0.0.1:8200;
}
server {
        listen 443 ssl;
        server_name c.osuserver.work.gd ce.osuserver.work.gd c4.osuserver.work.gd osu.osuserver.work.gd api.osuserver.work.gd;
        client_max_body_size 20M;

        ssl_certificate     /home/bjar-docker/.data/nginx/wildcard.crt;
        ssl_certificate_key /home/bjar-docker/.data/nginx/wildcard.key;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";

        access_log /home/bjar-docker/.data/nginx/bancho_access.log;
        error_log /home/bjar-docker/.data/nginx/bancho_error.log;

        location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP  $remote_addr;
                proxy_set_header Host $http_host;
                add_header Access-Control-Allow-Origin *;
                proxy_redirect off;
                proxy_pass http://bancho_backend;
        }
}

server {
        listen 443 ssl;
        server_name assets.osuserver.work.gd;

        ssl_certificate     /home/bjar-docker/.data/nginx/wildcard.crt;
        ssl_certificate_key /home/bjar-docker/.data/nginx/wildcard.key;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";

        access_log /home/bjar-docker/.data/nginx/assets_access.log;
        error_log /home/bjar-docker/.data/nginx/assets_error.log;

        location / {
                default_type image/png;
                root /home/bjar-docker/.data/server/data/assets;
        }
}

server {
        listen 443 ssl;
        server_name b.osuserver.work.gd;

        ssl_certificate     /home/bjar-docker/.data/nginx/wildcard.crt;
        ssl_certificate_key /home/bjar-docker/.data/nginx/wildcard.key;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";

        access_log /home/bjar-docker/.data/nginx/b_access.log;
        error_log /home/bjar-docker/.data/nginx/b_error.log;

        location / {
            return 301 https://b.ppy.sh$request_uri;    
        }
}

server {
        listen 443 ssl;
        server_name a.osuserver.work.gd;

        ssl_certificate     /home/bjar-docker/.data/nginx/wildcard.crt;
        ssl_certificate_key /home/bjar-docker/.data/nginx/wildcard.key;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";

        access_log /home/bjar-docker/.data/nginx/avatars_access.log;
        error_log /home/bjar-docker/.data/nginx/avatars_error.log;

        location / {
                root /home/bjar-docker/.data/server/data/assets/avatars;
                try_files $uri $uri.png $uri.jpg $uri.gif $uri.jpeg $uri.jfif /default.png = 404;
        }
}